server:
  port: 64416

spring:
  application:
    name: search-service

eureka:
  instance:
    instance-id: search-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka